# wrangler.toml

# Workerの名称。Cloudflareダッシュボードで表示される。
name = "llm-test-experience"

# 互換性日付。最新のWorkersランタイム機能を利用するために、最近の日付に設定する。
# 参考: https://developers.cloudflare.com/workers/platform/compatibility-dates/
compatibility_date = "2025-04-08"

# APIロジックなど、動的リクエストを処理するWorkerスクリプトのエントリーポイント。
main = "src/index.ts"

# 静的アセットの設定。Cloudflare Pagesの機能をWorkersに統合。
# https://developers.cloudflare.com/workers/static-assets/
[assets]
# ビルドプロセスによって生成された静的フロントエンドアセット（HTML, JS, CSSなど）が含まれるディレクトリ。
directory = "./dist"

# シングルページアプリケーション（SPA）のルーティングを有効にする設定。
# 存在しないパスへのナビゲーションリクエスト（例：/test/mmlu）に対して、
# 404を返す代わりにindex.htmlを返す。これにより、クライアントサイドルーティングが正常に動作する。
not_found_handling = "single-page-application"

# wrangler devコマンドでローカル開発サーバーを起動する際の設定。
[dev]
# ローカルマシンのポート番号
port = 8787
# ローカルネットワーク上の他のデバイスからのアクセスを許可するかどうか
ip = "0.0.0.0"